apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
    - name: BUILDER_IMAGE
      description: Image used to do the build
      default: quay.io/buildah/stable:v1.11.0
    - name: TLSVERIFY
      description: True or False for TLS Verificatoin
      default: "false"
    - name: target-namespace
      type: string
      description: The target project
  workspaces:
    - name: shared-data
      description: |
        shared workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: master
    - name: build-push
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/$(params.target-namespace)/cos:latest"
        - name: CONTEXT
          value: $(workspaces.source.path)/labs/Openshift/DevopsManagement
        - name: BUILDER_IMAGE
          value: "quay.io/buildah/stable:v1.11.0"
        - name: TLSVERIFY
          value: "false"
      runAfter:
        - git-clone
    - name: deploy-to-cluster
      taskRef:
        name: deploy-cm
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: target-namespace
          value: $(params.target-namespace)
      runAfter:
        - build-push
